name: Node CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macOS-11.0
    strategy:
      matrix:
        node-version: [8, 10, 12, 14, 15]

    steps:
    - uses: actions/checkout@v1
    - name: Node v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
    - name: ensure universal binary (arm64/x86_64)
      run: |
        file fsevents.node
        file fsevents.node | grep -q arm64 || (echo "arm64 binary not built"; exit 1)
        file fsevents.node | grep -q x86_64 || (echo "x86_64 binary not built"; exit 1)
      env:
        CI: true
